Lucas Sequence
a = 0, b=0, c=1 are the 1st three terms. All other terms in the Lucas sequence are generated by the sum of their 3 most recent 
predecessors. Write a program to generate the first n terms of a Lucas Sequence. Input format: The input containing an integer 'n' 
which denotes the given number Output format: Print the 'n' terms of the Lucas Sequence, separated by a single space. There are no 
leading or trailing spaces in the output.
Example 1:

Input: 

 
8


Output:

0 0 1 1 2 4 7 13

code:
 import java.util.*;
class Main{
  public static void main(String args[]){
  Scanner m=new Scanner(System.in);
  int n,a=0,b=0,c=1;
   n=m.nextInt();
  System.out.print(a+" "+b+" "+c+" ");
while(n!=3&&n>1){
  int d=a+b+c;
  System.out.print(d+" ");
    a=b;
  b=c;
  c=d;
  n--;
}
}
}
